# -*- coding: utf-8 -*-
"""localhostrun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u02l4Irjj4m8UZPIH7NmI_XnS86Dd_w7
"""

# Commented out IPython magic to ensure Python compatibility.

%cd /root/vorst-cavry

!python launch.py --listen --enable-insecure-extension-access --theme dark --no-half-vae --disable-console-progressbars --disable-safe-unpickle --no-hashing --opt-sdp-attention --localhostrun --skip-version-checkloudflared
